- name: Esecuzione script Wallapop e Vinted
        run: |
          python bot.py
          python vinted_bot.py

      - name: Salva e aggiorna i file su GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add seen_items.json seen_vinted_items.json
          git diff-index --quiet HEAD || git commit -m "Chore: aggiornati articoli visti [skip ci]"
          git push
